[package]
name = "example"
type = "contract"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]

# Framework import
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.23.0", directory = "yarn-project/aztec-nr/aztec" }
safe_math = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.23.0", directory = "yarn-project/aztec-nr/safe-math" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.23.0", directory = "yarn-project/aztec-nr/authwit" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.23.0", directory = "yarn-project/aztec-nr/compressed-string" }
easy_private_state = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.23.0", directory = "yarn-project/aztec-nr/easy-private-state" }
value_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.23.0", directory = "yarn-project/aztec-nr/value-note" }